### ISSUE TITLE
Mugshot is not showing

### ISSUE THREAD

**Issue by nelsyeung** [HumanityOnline/MyRefuge#11]
The current mugshot path starts with /vagrant/myrefuge rather than /myrefuge.

**Comment by cazgp** [comment]
That's only on dev. On prod it's not showing either, but for a different reason. Hmm. Atm we're using something called rednoise to serve media files, but I think we maybe should be uploading to S3 or GCE's equivalent of.

**Comment by nelsyeung** [comment]
Is there anyway of making it work for the dev?

**Comment by cazgp** [comment]
Install `django-storages` and configure it for Google Cloud Storage https://django-storages.readthedocs.org/en/latest/backends/apache_libcloud.html

**Comment by hoatle** [comment]
fixed on dev

**Comment by nelsyeung** [comment]
Looks like it's working now, thanks.
