### ISSUE TITLE
remote debugging support

### ISSUE THREAD

**Issue by hoatle** [HumanityOnline/MyRefuge#16]
```
[10/5/15, 4:59:28 AM] Nathan O'Hanlon: Finding it really hard to debug the code without a debugger working with pycharm, any chance of some guidance on how to set up debugging
[10/5/15, 8:43:45 AM] Hoat Le: sorry, not yet, maybe you should try to search how to remote debug with pycharm
```

**Comment by nathanlon** [comment]
If it is OK with Sholi I would like to pay Hoat for some training time in Django, mainly to learn how to debug his code with PyCharm and break points

**Comment by cazgp** [comment]
a) PyCharm itself costs quite a lot.
b) It's more useful to spend time on writing tests to catch any issues which may arise.

There's not a single test that I can see in the repo. That's far more relevant than learning an arbitrary method of debugging. Personally, I use vim and debug with ipdb, so each to their own really.

**Comment by hoatle** [comment]
@cazgp https://github.com/HumanityOnline/MyRefuge/issues/17 was created for tests

**Comment by hoatle** [comment]
docs added, done, closed https://github.com/HumanityOnline/MyRefuge/blob/master/docs/debugging.md#pycharm-intellij-with-python-plugin-installed
